### ISSUE TITLE
Erreur 404 openfisca

### ISSUE THREAD

**Issue by blackrez** [sgmap/cout-embauche#1]
Bonjour,

Openfisca retourne désormais un code 404 : 

```
{"apiVersion": 1, "error": {"message": "Path not found: /api/2/formula/accident_du_travail+famille+fnal+versement_transport+agff_salarie+agirc_salarie+apec_salarie+arrco_salarie+chomage_salarie+cotisation_exceptionnelle_temporaire_salarie+vieillesse_plafonnee_salarie+vieillesse_deplafonnee_salarie+mmid_salarie+csg_deductible_salaire+mhsup+csg_imposable_salaire+crds_salaire+sal+salaire_net_a_payer+salsuperbrut+ags+agff_employeur+apec_employeur+arrco_employeur+chomage_employeur+cotisation_exceptionnelle_temporaire_employeur+vieillesse_dep..._salaires+agirc_employeur+contribution_exceptionnelle_solidarite+ircantec_employeur+ircantec_salarie+exoneration_cotisations_employeur_zfu+exoneration_cotisations_employeur_zrr+exoneration_cotisations_employeur_zrd+allegement_fillon+exoneration_cotisations_employeur_apprenti+exoneration_cotisations_employeur_stagiaire+exoneration_cotisations_employeur_jei", "code": 404}}
```

**Comment by MattiSG** [comment]
On a déployé une mise à jour sur openfisca.sgmap.fr <http://openfisca.sgmap.fr/> avant-hier, il a du y avoir un renommage qui est passé à travers les mailles du filet. Je regarde ASAP.

**Comment by MattiSG** [comment]
Trouvé : le déploiement s’est fait sur une branche prod comprenant les commits nécessaires à mes-aides mais a entraîné une régression en ne contenant plus le commit 25c3b1abdf40d7df2cdefccf8f4351023dd97b57 de openfisca/openfisca-france.

Je vais créer une branche d’intégration temporaire qui parte de openfisca/openfisca-france#next en attendant que openfisca/openfisca-france#241 et openfisca/openfisca-france#242 soient intégrées.
