### ISSUE TITLE
Calculer les cotisations pour les apprentis

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#10]

**Comment by agathelenahenec** [comment]
Pour pouvoir calculer les cotisations des apprentis, il convient de faire évoluer l'interface : si l'employeur est artisan ou commerçant (avec moins de 11 salariés apprentis non compris), il bénéficie d'une exonération totale de cotisations. Les autres employeurs ne bénéficient que d'une exonération partielle.

**Comment by laem** [comment]
Voir la décision de #178
