### ISSUE TITLE
Vue détaillée

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/cout-embauche#100]
Bonjour,

Juste pour vous dire que j'aurais un grand intérêt à pouvoir visualiser facilement le barème détaillé, façon feuille de paie classique (base, taux détaillés, tranches).
Ce serait très pratique pour contrôler les fiches de paie que j'émet ou mes saisies URSSAF.fr, et ça m'éviterai d'avoir à refaire le travail dans un tableur.
Avec des agrégats c'est difficile de se faire un idée et de comprendre les divergences que j'observe.

Jérôme

**Comment by laem** [comment]
J'ai remarqué que par rapport à un certain nombre de fdp, nous agrégeons moins les cotisations (e.g. retraite ARRCO et AGIRC confondues pour les cadres). 
Par contre, comme tu le dis, nous ne donnons pas les informations chiffrées (base, taux, tranches) et je pense qu'actuellement open fisca ne gère pas cela (API de calcul, pas API de compréhension des calculs). Ce serait très intéressant, notamment un moyen de garantir les calculs, mais un gros sujet open fiscaje pense.

**Comment by MattiSG** [comment]
Hello @jdesboeufs et merci pour la suggestion !

Il y a ambiguïté dans ton retour : parles-tu d'_agrégats de lignes_ (réunir plusieurs cotisations en une) ou d'_agrégats de colonnes_ (ne pas afficher assiette + taux mais seulement le montant final) ?

**Comment by jdesboeufs** [comment]
Je pensais surtout aux colonnes, car pour remplir le bordereau URSSAF en ligne on demande les assiettes (il n'y a pas de calcul automatique), et car c'est intéressant de pouvoir comparer les taux avec ses fiches de paie, ses logiciels ou les différentes sources en ligne (hélas divergentes).

**Comment by MattiSG** [comment]
Ouaip, c'est ce qu'il me semblait. Pour les lignes, il n'y a pas d'uniformisation, ça pourrait venir avec les recommandations du [rapport sur la clarification du bulletin de paie](http://travail-emploi.gouv.fr/IMG/pdf/21072015_rapportclarification_BP.pdf) :

> Recommandation n°1 : Construire un référentiel des intitulés de paie et le rendre public par arrêté ministériel
> Recommandation n°2 : Rendre ces intitulés accessibles sur le site internet servicepublic.fr

@laem On a effectivement un (très fort) intérêt à rendre OpenFisca capable d'expliquer ses calculs… Mais c'est non trivial. En attendant, tu peux regarder `intermediateVariables` (@jdesboeufs pourra probablement t'en dire plus), mais ça ne répond pas à la problématique de découvrir les dépendances. Éventuellement avec l'API `fields`, et là c'est @cbenz qui pourrait aiguiller. Mais encore une fois, pas moyen de faire de découvrabilité automatique entre dépendance à afficher et dépendance purement technique.

**Comment by laem** [comment]
Voir #100

**Comment by laem** [comment]
Voir https://github.com/sgmap/cout-embauche/wiki/Nouvelle-syntax-des-regles
