### ISSUE TITLE
Regrouper les détails par organisme de recouvrement

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#101]
Utile dans une version plus avancée. Objectif d'aide à la vérification / rédaction de fiche de paie / déclaration des cotisations (e.g. URSSAF).
@jdesboeufs @agathelenahenec

**Comment by MattiSG** [comment]
Attention, pour la rédaction de fiche de paie ce sera faux si les recommandations du [rapport sur la clarification du bulletin de paie](http://travail-emploi.gouv.fr/IMG/pdf/21072015_rapportclarification_BP.pdf) sont suivies :

> Recommandation n°3 : Regrouper les lignes de cotisations de protection sociale par risque couvert.

**Comment by laem** [comment]
Il faudrait en effet que ce soit une *vue* possible des cotisations détaillées

**Comment by laem** [comment]
Ce qui nous donne donc une vue employeur et une vue employé (celle-ci étant déjà recommandée par ce rapport).

**Comment by laem** [comment]
Voir #126

**Comment by laem** [comment]
Voir https://github.com/sgmap/cout-embauche/wiki/Nouvelle-syntax-des-regles
