### ISSUE TITLE
 Calculer les cotisations pour les associations

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#102]

**Comment by laem** [comment]
Il n'y a pas de spécificités pour les associations !

[source](http://www.netpme.fr/info-conseil-2/question-entrepreneur/droit-travail/question-entrepreneur/39185-existetil-des-specificites-en-matiere-de-gestion-de-la-paie-quand-on-est-une-association)

> En matière de paie et plus particulièrement pour ce qui concerne les bulletins de paie, il n'existe pas de spécificité liée au fait d'être une association (les dispositions du code du travail s'appliquent à toutes les personnes salariées ou travaillant à quelque titre ou en quelque lieu que ce soit pour un ou plusieurs employeurs et quels que soient le montant et la nature de leurs rémunérations, la forme, ou la validité de leur contrat, selon l'article L3243-1). Une association a donc les mêmes obligations de respect du droit du travail qu'une entreprise, et notamment en ce qui concerne l'établissement des bulletins de paie. Ces derniers sont donc les mêmes que pour une société et la convention collective applicable est celle du secteur d'activité concerné.

> En application du code de la propriété intellectuelle, toute reproduction totale ou partielle est strictement interdite sans autorisation écrite de NetPME.

**Comment by laem** [comment]
Message du 18 février 2016 remettant en cause le commentaire précédent et la fermeture de cette _issue_ : 

L'outil de simulation n'est pas adapté pour les associations. 
 
Le calcul pour l'embauche d'un salarié  dans une association comporte notamment les erreurs suivantes :  
 - taxe d'apprentissage à supprimer
 - effort construction à supprimer
 - CICE à supprimer
 - Aide pour le premier salarié à supprimer
 
 - taxe sur les salaires à calculer

**Comment by benjello** [comment]
La taxe sur les salaires est déjà présente.

**Comment by laem** [comment]
C'est exact, j'ai corrigé : "à intégrer" :+1:

**Comment by laem** [comment]
Sources et vérifications : 

- L'effort construction est à payer pour les assos : http://www.associations.gouv.fr/663-les-autres-taxes.html
- Le CICE n'est en effet pas prévu. 
- La taxe d'apprentissage est en effet à enlever pour les associations à but non lucratif : http://www.associations.gouv.fr/701-l-association-et-les-impots.html
- Aide pour le premier salarié : si ! 
http://travail-emploi.gouv.fr/grands-dossiers/plan-tpe-pme/faq-aide-a-l-embauche-du-premier-salarie/
> Oui, les associations sont assimilées à des entreprises en tant qu’employeurs de droit privé.
