### ISSUE TITLE
Ne pas injecter de CSS globale

### ISSUE THREAD

**Issue by MattiSG** [sgmap/cout-embauche#11]
Possibilités (non mutuellement exclusives) :
- Loader [`local-scope`](https://github.com/webpack/css-loader#local-scope) ([contexte](https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284)).
- Préfixe `.SGMAPembauche` manuel.
- Préfixe `.SGMAPembauche` avec [`postcss-prefix-selector`](https://github.com/jonathanong/postcss-prefix-selector).
- [BEM](https://en.bem.info).

**Comment by laem** [comment]
L'approche local-scope de Webpack avec en plus les CSS Modules (qui permette d'écrire un fichier CSS avec le scope local implicite et éviter de répeter les :local(.maClasse) ) est très intéressante pour une app js qui importe des templates (ou particulièrement avec React où les "templates" sont directement écrits dans les .js)
Vu que embauche charge (pour l'instant) un gros fichier .html, partons sur postcss-prefix avec le loader Webpack postcss.
Cela suppose de transférer le CSS de body dans un nouveau tag content.

**Comment by laem** [comment]
- Ids should be removed, as they can conflict with the host page's. 
- BEM with [”Sans underscore“ style](https://en.bem.info/method/naming-convention/#alternative-naming-schemes) will be used, e.g. blockName-elemName--modName--modVal.
