### ISSUE TITLE
Ambiguité de la saisie effectif

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#110]
L'effectif est notamment pris en compte pour calculer les cotisations suivantes : 
1) Formation professionnelle (changement de taux au dessus de 10)
2) Allègement Fillon (changement de taux au dessus de 20)
3) AT/MP (<20, < 150, >=150)
4) Versement transport (rien en dessous de 10)
 
Malheureusement, ces cotisations ne parlent pas du même effectif : 

Pour 1) et 2), c'est bien l'effectif de l'entreprise. 
Pour 3), c'est aussi l'effectif de l'entreprise mais le calcul dépend de l'établissement d'embauche.
> L'établissement est une unité de production géographiquement individualisée, mais juridiquement dépendante de l'entreprise. Un établissement produit des biens ou des services : ce peut être une usine, une boulangerie, un magasin de vêtements, un des hôtels d'une chaîne hôtelière, la « boutique » d'un réparateur de matériel informatique...
> L'établissement, unité de production, constitue le niveau le mieux adapté à une approche géographique de l'économie. (léxique INSEE)
Pour 4), c'est, selon service-public.fr, 
> tous établissements confondus dans une même zone de transport

Pour calculer le versement transport, nous allons donc faire l'approximation effectif entreprise = effectif établissements de la zone de transport. Notre erreur serait donc d'afficher un taux non nul pour une entreprise de plus de 10 employés mais embauchant dans une zone contenant moins de 9 employés. 

Pour le taux AT/MP, il est nécessaire de préciser le fait que le taux va dépendre de l'établissement.

**Comment by MattiSG** [comment]
Oui… mais ne bloquons pas pour autant la livraison d’AT/MP et VT, avec les approximations effectivement soulevées  :wink:

**Comment by laem** [comment]
Bien sûr !

**Comment by laem** [comment]
Voir le wiki : 
https://github.com/sgmap/cout-embauche/wiki/Effectif-de-%3F
