### ISSUE TITLE
Taux réduit de la cotisation d'allocations familiales

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/cout-embauche#113]
Bonjour,

Je viens de m'arracher les cheveux pendant une bonne heure en comparant mon barème et votre barème, mais je viens de trouver !

Depuis le 1er janvier 2015 et l'application du [Pacte de Solidarité et de Responsabilité](https://www.urssaf.fr/portail/home/employeur/beneficier-dune-exoneration/exonerations-generales/la-reduction-generale.html), il y a de [nouvelles dispositions](https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/la-cotisation-dallocations-famil/la-reduction-du-taux-de-la-cotis.html).

Maintenant il y a deux taux :
* le taux "abaissé" : __3,45 %__
* le taux "normal" : __5,25 %__

Le nouveau __taux abaissé__ s'applique pour les salariés dont le salaire sur l'année est __inférieur à 1,6 fois le SMIC__ ET __relevant du régime obligatoire d'assurance chômage__ ([ce qui exclus d'office les mandataires sociaux](http://www.legisocial.fr/actualites-sociales/1323-les-mandataires-sociaux-ne-peuvent-beneficier-du-taux-reduit-de-cotisations-dallocations-familiales.html)).

Là où ça se complique, c'est que le taux recouvré immédiatement est le __taux abaissé__.
La régularisation se fait par l'URSSAF en début d'année suivante, car on ne sait pas avant la fin de l'année quel est le taux à appliquer.

Bref du coup il me semble que le simulateur affiche le mauvais montant pour les salaires inférieurs à 1,6 SMIC, et que pour les autres cas il faut trouver un moyen d'afficher le montant de la régularisation, et/ou le taux "réel".

Bon courage, et merci aux nains qui ont pondu cette horreur ...

**Comment by laem** [comment]
Corrigé (détails dans #144) ! En effet c'est complexe... 
Etant donné que nous simulons une embauche à salaire fixe sur 12 mois, on peut calculer facilement la réduction. Mais si un jour on se penche sur la déclaration effective pour l'URSSAF, il faudra distinguer les deux oui.
