### ISSUE TITLE
Supprimer les allocations temporaires d'invalidité

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#12]
Il n'y a pas me semble-t-il de cotisation spécifique pour le risque invalidité car celui-ci est inclus dans le risque maladie. Je ne m'explique pas la présence de cette ligne.

**Comment by MattiSG** [comment]
Il s'agit de la cotisation [`allocations_temporaires_invalidite`](http://legislation.openfisca.fr/variables/allocations_temporaires_invalidite). Peut-être s'agit-il d'un élément à rajouter dans #16 ?

**Comment by agathelenahenec** [comment]
Oui on peut l'ajouter là. Cette allocation est versée aux fonctionnaires en situation d'invalidité mais ne donne pas lieu me semble-t-il à une cotisation spécifique. En tout état de cause, ça n'a pas sa place dans un simulateur d'embauche.

**Comment by MattiSG** [comment]
Ah, ce n'est carrément pas une cotisation ! Du coup, ça n'est pas vraiment le même sujet que #16 où il s'agit de supprimer des lignes de cotisation spécifiques au secteur public.

Je rouvre l'issue et j'en profite pour notifier @benjello que la décomposition paie de l'IPP a probablement la même erreur puisque c'est de là que provient la liste des cotisations présentées dans le simulateur.

**Comment by benjello** [comment]
C'est une cotisation pour qui finance l'ATI des es agents des collectivités locales https://www.cdc.retraites.fr/portail/spip.php?page=article&id_article=183&cible=_employeur

**Comment by MattiSG** [comment]
Bon, alors on re-revient sur la proposition précédente et ça va bien dans #16  ;)

@benjello Peut-être faudrait-il envisager de renommer ces `allocations` pour que le nom de la variable prête moins à confusion… ? Ou en tous cas d'améliorer un tout petit peu la doc, ou mettre le lien.
Merci de ton aide en tous cas !

**Comment by benjello** [comment]
@MattiSG  be my guest ;-)
Plus sérieusement, si on trouve un lien plus "standard", oui il faut le rajouter.

**Comment by MattiSG** [comment]
> be my guest

Les PR de renommage sont autorisées maintenant ?  ;)

**Comment by agathelenahenec** [comment]
@MattiSG Ok! c'est une cotisation spécifique aux agents des CT je l'avais pas vue my mistake. Ceci dit je crois quand même qu'on peut à ce stade retirer cette ligne de l'outil non? Ca n'est pas vraiment notre cible.

**Comment by MattiSG** [comment]
Tout à fait, on l'inclut dans #16 !
