### ISSUE TITLE
Embauche ou coût du travail ?

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#120]
Le texte actuel du simulateur est : 
> Mon entreprise de `9` salariés souhaite rémunérer un salarié à hauteur de `1457,52` [...]

L'utilisateur doit donc comprendre que nous lui proposons de simuler le cout du travail de l'un de ses *employés actuels*, et que s'il veut embaucher un nouveau salarié, il faut qu'il remplisse l'"effectif de son" entreprise avec l'effectif de son entreprise + 1. 

Or le simulateur se veut être un simulateur de coût d'*embauche* et non de *cout du travail*...

**Comment by laem** [comment]
#89 en dépend

**Comment by MattiSG** [comment]
Remplacer « rémunérer un salarié à hauteur de » par « embaucher un salarié rémunéré » et ajouter +1 avant l’envoi de la requête à OpenFisca ?

**Comment by laem** [comment]
Exactement ce que je pensais :+1:
