### ISSUE TITLE
"Corriger ces résultats" should be a <a>

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#139]

**Comment by MattiSG** [comment]
:-1: Utiliser un bouton était volontaire en termes UX. Oui, c’est un lien car on change d'interface, mais c’est un CTA, et le contexte est préservé (on va tester la simulation actuellement présentée à l’utilisateur). L'objectif est d'avoir une action usager, le bouton pousse plus à cela.

**Comment by laem** [comment]
D'acc !
