### ISSUE TITLE
MAJ taux versement transport

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#14]
Le calcul de ce versement (assujetissement et taux) dépend de la variable géographique (taux différent dans chaque commune, non assujettissement en dehors des zones de transport urbain). Si on veut conserver cette ligne, nécessité de récupérer la commune d'implantation de l'entreprise (via le numéro SIRET?). Voir si cette évolution est opportune

**Comment by agathelenahenec** [comment]
#41

**Comment by laem** [comment]
Le [tableau des taux](https://fichierdirect.declaration.urssaf.fr/TablesReference.htm) par l'urssaf

**Comment by MattiSG** [comment]
Discussion à avoir en OpenLab : la localisation de l'entreprise est-elle une entrée « primaire » (bloc de saisie actuel) ou « secondaire » (bloc de saisie qui permet d'affiner la situation) ?

**Comment by laem** [comment]
TODO : mettre à jour les taux du versement transport (actuellement 2014). 
Nous attendons une réponse de l'urssaf. 
Possibilité aussi d'utiliser le widget.
