### ISSUE TITLE
Temps partiel

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#148]
Voir la page du wiki [Temps de travail](https://github.com/sgmap/cout-embauche/wiki/Temps-de-travail) pour le contexte.
Voir la page [Temps partiel](https://github.com/sgmap/cout-embauche/wiki/Calcul-du-temps-partiel) sur le wiki. 

- Travailler la saisie. 

- Implémenter le calcul. 

- Notamment, le temps partiel casse certaines cotisations ou aides
  - La réduction générale
  - GMP
  - ...

http://www.capital.fr/retraite/actualites/cadres-a-temps-partiel-attention-a-vos-cotisations-de-retraite-1046326

**Comment by laem** [comment]
Voir #85

**Comment by laem** [comment]
L'indication actuelle à la saisie du salaire, 
![selection_021](https://cloud.githubusercontent.com/assets/1177762/12921316/f433ab06-cf4c-11e5-9960-1d9d45a48bef.png)
laisse penser que le temps partiel est géré. Or il l'est mal, notamment sur le sujet de l'allègement général.

**Comment by georges-bayard** [comment]
Prendre en compte sur la règle selon laquelle la cotisation Garantie Minimale de Points est calculée en fonction du nombre d’heures travaillées pour les salariés à temps partiel
En 2016, la cotisation forfaitaire est fixée à 68,07 euros par mois. 
source : mail du mardi 9 février 2016 15:35

**Comment by georges-bayard** [comment]
Tu as fait la correction ? parceque moi je vois ça !


[cid:image001.png@01D163F4.BC8DBA70]

De : Mael [mailto:notifications@github.com]
Envoyé : mardi 9 février 2016 16:49
À : sgmap/cout-embauche
Objet : [***] Re: [cout-embauche] Temps partiel (#148)


L'indication actuelle à la saisie du salaire,
[selection_021]<https://cloud.githubusercontent.com/assets/1177762/12921316/f433ab06-cf4c-11e5-9960-1d9d45a48bef.png>
laisse penser que le temps partiel est géré. Or il l'est mal, notamment sur le sujet de l'allègement général.

**Comment by georges-bayard** [comment]
demande CCI d'implémenter des contrôles lors des simulations à moins de 24 heures pour les temps partiels (mail Florence Levasseur 03/04/2016)
Réponse : Idée à garder mais délicate à mettre en œuvre. 1 / on ne peut pas faire du contrôle bloquant car il y a des exceptions ; 2 / si le contrôle n’est pas bloquant généralement il n’est pas lu
