### ISSUE TITLE
Aide embauche PME (annonce François Hollande 18 janv 2016)

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#149]
http://www.lesechos.fr/economie-france/social/021627644622-plan-emploi-suivez-en-direct-les-annonces-de-francois-hollande-1193192.php#xtor=CS1-33

**Comment by laem** [comment]
Comment l'exprimer sans capturer la durée du contrat ?

**Comment by MattiSG** [comment]
En séparant les catégories CDI / CDD < 6 mois / [CDD ≥ 6 mois](http://travail-emploi.gouv.fr/grands-dossiers/embauchepme) ?

**Comment by laem** [comment]
Merci pour le lien, j'avais mal compris l'aide. Elle est donc très similaire à l'aide à la première embauche (pour laquelle nous avons omis de demander la durée du contrat) et donc facile à implémenter. 
Mais du coup, est-ce qu'elles se cumulent ? Probablement non !

**Comment by laem** [comment]
![selection_011](https://cloud.githubusercontent.com/assets/1177762/12551424/a4d00fc0-c36a-11e5-83a5-bcd0ed75196b.png)
http://travail-emploi.gouv.fr/grands-dossiers/plan-tpe-pme/faq-aide-a-l-embauche-du-premier-salarie/

**Comment by georges-bayard** [comment]
[decret_aide_embauche.pdf](https://github.com/sgmap/cout-embauche/files/124783/decret_aide_embauche.pdf)

**Comment by laem** [comment]
Réponse pour le cumul avec l'aide 1er sal : non. 
[Questions-réponses travail-emploi](http://travail-emploi.gouv.fr/IMG/pdf/qr-embauche-pme.pdf)
