### ISSUE TITLE
Supprimer les lignes spécifiques aux agents publics

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#16]
La ligne "contribution exceptionnelle de solidarité" de même que les deux lignes IRCANTEC ne concernent que les agents publics.

**Comment by agathelenahenec** [comment]
Supprimer également la ligne "Invalidité"

**Comment by MattiSG** [comment]
> Supprimer également la ligne "Invalidité"

Cela sera traité indépendamment dans #12.

**Comment by MattiSG** [comment]
> Cela sera traité indépendamment dans #12.

En fait non, cf. discussion dans #12.
