### ISSUE TITLE
Capturer les retours utilisateur

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#162]
Deux types de retour utilisateur sont possibles. 
-  déclarer une erreur dans les calculs. Précisément : nous affichons une valeur erronée pour une des lignes, l'utilisateur propose une valeur corrigée. 

> Ce que l'on doit lui présenter, c'est une possibilité d'éditer des valeurs affichées dans les cotisations détaillées, de justifier la correction, de la valider et d'obtenir un lien qui lui permettra de suivre l'évolution de son retour.

Comme expliqué dans df921e4b51064e5a169318dce240801b101598ef, le lien de création de test ludwig qui était présent sous les cotisations détaillées a été remplacé fin janvier 2015 par un bouton d'envoi de mail. 
En attendant cette intégration des retours d'erreurs, nous pouvons nous même créer manuellement un test dans ludwig et une issue tagguée `fiabilisation` correspondante, puis communiquer ces liens par retour de mail à l'utilisateur.
Il faut pour cela mettre à jour la description des cotisations dans Ludwig #93 et changer l'url de l'instance openfisca pour openfisca-embauche.sgmap.fr
-  suggérer l'ajout d'une ligne, l'ajout d'une saisie (ex. le temps partiel), ou tout autre commentaire sur le simulateur. 
  Cela peut-être géré : 
  - par des mails, avec potentiellement une réponse contenant un lien vers une issue sur cout-embauche
  - ou avec la création automatique d'issues sur un deuxième repo de retours utilisateurs, liées ensuite aux issues de cout-embauche (non prioritaire)

**Comment by MattiSG** [comment]
Go !

- [ ] mettre à jour la description des cotisations dans Ludwig
- [ ] changer l'url de l'instance openfisca pour openfisca-embauche.sgmap.fr
- [ ] former Georges à l'utilisation de Ludwig

**Comment by laem** [comment]
Suite à une tentative de création manuelle de tests, j'abandonne cette idée. J'y passe plus de temps qu'à corriger les erreurs elles-mêmes.

**Comment by MattiSG** [comment]
Qu'est-ce que tu abandonnes ? Comment prévois-tu de capturer les retours utilisateurs ?

**Comment by laem** [comment]
Il y a aujourd'hui un simple bouton de retour d'erreurs par mail. 
Remettre les tests demandera un certain temps.
