### ISSUE TITLE
prendre en compte l'effectif pour le calcul de la participation à l'effort de construction

### ISSUE THREAD

**Issue by georges-bayard** [sgmap/cout-embauche#166]
le simulateur ne prend pas en compte l'effectif salarié pour le calcul de la cotisation employeur participation à l'effort de construction (plus de 20 salariés)
https://www.service-public.fr/professionnels-entreprises/vosdroits/F22583

**Comment by laem** [comment]
En cours : https://github.com/openfisca/openfisca-france/pull/430

**Comment by laem** [comment]
Corrigé :sunglasses:

**Comment by georges-bayard** [comment]
Cool
