### ISSUE TITLE
prise en compte de l'effectif pour le calcul de la  la contribution supplémentaire à l'apprentissage  

### ISSUE THREAD

**Issue by georges-bayard** [sgmap/cout-embauche#167]
la contribution à l'apprentissage n'est pas due pour les entreprises de moins de 250 salariés. Dans le simulateur le calcul est déclenché pour les entreprises quelle que soit leur taille.
http://www.adefim-idf.org/apprentissage/aide-ta/contribution-supplementaire-a-l-apprentissage--.html

**Comment by bChiquet** [comment]
Le lien précédemment fourni est 404. 
http://bofip.impots.gouv.fr/bofip/6325-PGP.html

**Comment by laem** [comment]
Merci pour le lien ! Il y a aussi [celui-là](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22574). 
Cette contribution supplémentaire sera prise correctement en compte une fois le travail de la branche `advanced` terminé.
