### ISSUE TITLE
Corriger les cotisations ARRCO salarié

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#17]
Sur la tranche 2 des cotisations ARRCO salarié (salaires bruts supérieurs à 3170€) erreur : seule la tranche 1 est comptabilisée cf test ARRCO salarié non cadre salaire brut 9510€.
Ajouter la tranche 2 = sur la part de salaire comprise entre 3170€ et 9510€ un taux de 8,10%
http://www.irp-auto.com/entreprises/gerez-votre-entreprise/calcul-des-cotisations-ce-que-vous-devez-savoir

**Comment by agathelenahenec** [comment]
Bizarre car cette erreur n'apparaît que sur la tranche 1 et pas sur la tranche 2. Il faudrait vérifier la formule de calcul

**Comment by agathelenahenec** [comment]
Sur la tranche 2 des cotisations ARRCO salarié (salaires bruts supérieurs à 3170€) erreur : seule la tranche 1 est comptabilisée

**Comment by MattiSG** [comment]
Merci ! Peux-tu stp mettre un lien vers les tests associés en créant une issue ?

Ici, par exemple: http://embauche.sgmap.fr/tests/55c382a46149d1903b3d2d82/show

Cette URL est celle qui apparaît dans la barre d'adresse du navigateur après la création ou l'édition du test, et peut être retrouvée par le lien "Permalien" en bas en déroulant le test dans la liste.

Cela facilite beaucoup le travail pour retrouver le test  :)

**Comment by agathelenahenec** [comment]
ok pas de problème

**Comment by agathelenahenec** [comment]
Les cotisations AGIRC n'apparaissent pas du tout. Elles sont en partie reportées sur les lignes ARRCO mais même comme ça le montant est faux. Cela induit de très gros écarts. A corriger en priorité avec le Fillon.

http://embauche.sgmap.fr/tests/55c47f3b6149d1903b3d3dd2/show

**Comment by MattiSG** [comment]
@agathelenahenec Dans [ce test](http://embauche.sgmap.fr/tests/55c381086149d1903b3d2d18/show),  toutes les lignes sont testées. Je ne sais pas lesquelles doivent réellement l'être. Pourras-tu le modifier pour effacer celles qui ne sont pas concernées ?  :)

**Comment by agathelenahenec** [comment]
@MattiSG Je ne vois que deux lignes quand j'essaie de le modifier..

**Comment by agathelenahenec** [comment]
C'est ce test là pour cette issue : http://embauche.sgmap.fr/tests/55c382a46149d1903b3d2d82/show

**Comment by MattiSG** [comment]
> Je ne vois que deux lignes quand j'essaie de le modifier..

Effectivement, c'était encore un coup de sgmap/ludwig-ui#27, désolé !

**Comment by laem** [comment]
Corrigé dans openfisca
