### ISSUE TITLE
GMP

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#18]
Pour les salariés cadre dont le salaire est inférieur à 3492,82€ (salaire charnière réévalué chaque année), est prévue une garantie minimum de points (GMP) AGIRC. Cette garantie est financée par une cotisation sur la part de salaire incluse entre le plafond de la Sécurité sociale (3170€ brut en 2015) et 3492,82.
Donc si cadre avec salaire inférieur à 3492,82€, cotisation = à 66,34€ dont 41,17 pour l'employeur et 25,17 pour le salarié.
Formule de calcul : 
Part patronale : (Salaire charnière - plafond de la sécurité sociale)* 12,75%
Part salariale : (Salaire charnière - plafond de la sécurité sociale)* 7,80%

http://www.editions-tissot.fr/actualite/droit-du-travail-article.aspx?secteur=PME&id_art=6186&titre=GMP+%28garantie+minimale+de+points%29+2015

**Comment by laem** [comment]
Les taux dans OpenFisca : https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/param/param.xml#L288-L335

**Comment by laem** [comment]
Cette cotisation est déjà implémentée dans open fisca et prise en compte dans le salaire net. Il nous suffit de l'ajouter dans l'interface.

**Comment by agathelenahenec** [comment]
great news

**Comment by laem** [comment]
J'ai oublié d'ajouter la part employeur :-1:
