### ISSUE TITLE
adapter l'outil aux associations

### ISSUE THREAD

**Issue by georges-bayard** [sgmap/cout-embauche#187]
L'outil de simulation n'est pas adapté pour les associations. Message du 18 février 2016 : 
 
Le calcul pour l'embauche d'un salarié  dans une association comporte notamment les erreurs suivantes :  
  - taxe d'apprentissage à supprimer
 - effort construction à supprimer
 - CICE à supprimer
 - Aide pour le premier salarié à supprimer
 
 - taxe sur les salaires à calculer

**Comment by laem** [comment]
:+1: Il semblerait que je me sois bien trompé en fermant l'issue #102

**Comment by georges-bayard** [comment]
Tu le rouvres et tu réintègre la remarque du Monsieur dedans ?

De : Mael [mailto:notifications@github.com]
Envoyé : mardi 23 février 2016 14:26
À : sgmap/cout-embauche
Cc : BAYARD Georges
Objet : Re: [cout-embauche] adapter l'outil aux associations (#187)


[:+1:]Il semblerait que je me sois bien trompé en fermant l'issue #102<https://github.com/sgmap/cout-embauche/issues/102>
