### ISSUE TITLE
Ajouter la ligne "assurance décès"?

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#19]
Il s'agit d'une prévoyance prévue par la convention collective des cadres de 1947. Elle s'applique à tous les cadres ainsi qu'aux VRP exclusifs. La cotisation est à la charge de l'employeur, d'un taux de 1,5%, sur le montant du plafond de la sécurité sociale. Elle est recouvrée par l'AGIRC.

Ceci dit peut-on vraiment la considérer comme obligatoire ?
"Dans le cas où l’entreprise ne respecte pas cette obligation, elle doit, en cas de décès, verser aux ayants droit un capital dont le montant est égal à 300 % du plafond annuel de la sécurité sociale."

A voir avec les partenaires peut-être au cours d'un prochain open lab

http://www.retraite-entreprises.agirc-arrco.fr/agircarrcoportail/index.php/Accompagner/Evenements-de-la-vie/Deces

**Comment by laem** [comment]
Précédemment dans "Main d'oeuvre"

**Comment by jdesboeufs** [comment]
Je confirme qu'elle est obligatoire pour les cadres et les assimilés-salariés (dirigeants).
Par contre elle n'est pas recouvrée par l'AGIRC mais par des organismes de prévoyance qui prennent contact avec les entreprises dès leur création (ce qui est mon cas en ce moment, et l'avait été lors de ma précédente création).
Ces organismes de prévoyance en profite généralement pour essayer de vendre des garanties complémentaires qui se retrouvent aussi sur la fiche de paie, sur les tranche A et B.

**Comment by jdesboeufs** [comment]
Mais oui on peut "se mettre en infraction", c'est la cas de pas mal d'autres cotisations d'ailleurs.

**Comment by agathelenahenec** [comment]
ok on garde alors et en plus elle est déjà calculée ça serait dommage de s'en priver. à afficher en tant que tel donc

**Comment by laem** [comment]
Référence du calcul : http://legislation.openfisca.fr/variables/prevoyance_obligatoire_cadre

**Comment by laem** [comment]
Quel nom serait le plus adapté du coup, "Assurance décès cadre" ou "Prévoyance obligatoire cadre" ? @jdesboeufs @agathelenahenec

**Comment by jdesboeufs** [comment]
Prévoyance obligatoire cadre, car souvent le contrat minimal est plus large
que l'assurance décès (il y a en général l'invalidité).

**Comment by laem** [comment]
:+1:
