### ISSUE TITLE
Différence communication du gouvernement

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#192]
Investiguer la différence entre les résultats du simulateur et l'infographie du gouvernement. 

![exemples-concrets](https://cloud.githubusercontent.com/assets/1177762/13458524/033fcbe8-e06e-11e5-9528-00a1a226695c.png)
http://travail-emploi.gouv.fr/grands-dossiers/embauchepme/article/entreprises-de-moins-de-250-salaries-decouvrez-la-prime-embauche-pme#Est-ce-cumulable-avec-d-autres-aides

Nous avons une légère différence (1.4€) sur les réductions générale et allocs, et une différence importante sur les cotisations employeur de droit commun, non détaillées dans l'infographie.

**Comment by georges-bayard** [comment]
la grosse différence se situe sur le deuxième exemple (embauche de Sarah) pour lequel une différence de 38 euros est notée entre le simulateur et l'estimation sur les charges patronales (779 euros sur le doc de com et 817 euros sur le simulteur). La DGEFP est alertée et recherche les éléments qui ont servi de base au calcul.
Sur le reste les chiffres sont les mêmes.

**Comment by laem** [comment]
La divergence venait d'hypothèses différentes sur les attributs de l'entreprise.
