### ISSUE TITLE
Renommer lignes ASSEDIC/Assurance chômage

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#20]
Pour plus de clarté et de cohérence avec les autres lignes, il conviendrait de nommer ces lignes

Assurance chômage (ex ligne ASSEDIC)
Assurance chômage (salarié) (ex ligne Assurance chômage)

**Comment by MattiSG** [comment]
Dans la mesure où la cotisation salarié est sous le titre Salarié, il est très étrange à la lecture de voir cette mention répétée entre parenthèses.

Sauf avis contraire, j'uniformise sur « Assurance chômage » pour les deux types.
