### ISSUE TITLE
Corriger le taux de la ligne Allocations familiales pour les salaires inférieurs à 1,6 SMIC

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#22]
Depuis le 1er janvier 2015, la cotisation AF a été réduite pour les employeurs entrant dans le champ du Fillon et pour les salariés < 1,6 SMIC.
Le taux dans ces cas là n'est que de 3,45% au liue de 5,25% sur la totalité du salaire pour les autres salariés.
http://embauche.sgmap.fr/tests/55c4c4d06149d1903b3d4597/show

http://www.urssaf.fr/general/actualites/actualites_generales/baisse_de_la_cotisation_dallocations_familiales_01.html

**Comment by laem** [comment]
Le lien urssaf donne une erreur 404, j'imagine que celui là est équivalent : http://www.paris.urssaf.fr/general/actualites/actualites_generales/baisse_de_la_cotisation_dallocations_familiales_01.html

**Comment by agathelenahenec** [comment]
Oui c'est équivalent, merci :)

**Comment by laem** [comment]
Fait, voir #144
