### ISSUE TITLE
[Bug] calcul temps partiel erroné

### ISSUE THREAD

**Issue by loudoweb** [sgmap/cout-embauche#221]
Si temps partiel = 35h, les données correspondent au temps complet. Donc ok.

MAIS si on met moins, genre 24h. On se retrouve avec un coût supérieur au temps complet pour l'entreprise et un net plus élevé pour le salarié. Les 2 montants devraient être inférieurs aux montants du temps complet.

**Comment by laem** [comment]
Oui, bien vu !
Si l'on change le nombre d'heures par semaine à salaire constant, le salarié aura un salaire horaire plus élevé, ce qui le conduira à payer d'avantage pour certaines cotisations comportant un plafond. 
Au sujet du net plus élevé, je vais regarder cela en détail. 
Afficher le détail du calcul des cotisations (assiette et taux) dans les résultats détaillés (ou en tout cas permettre d'aller plus loin) permettrait de clarifier ce comportement.

**Comment by laem** [comment]
Au sujet du net plus élevé pour un temps partiel, cela s'explique essentiellement par la cotisation vieillesse plafonnée : son plafond est proratisé pour le temps partiel (même si le salarié a la possibilité de ne pas le faire), ce qui mène à une cotisation plus faible et donc un salaire net plus élevé ! Avec en contrepartie, une retraite moins avantageuse.
