### ISSUE TITLE
Corriger le taux cotisation patronale Maladie à 13,1% (et non 12,8%)

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#23]
La formule de calcul doit prévoir un taux de 12,8%. Il faut la modifier pour mettre 13,1%

http://embauche.sgmap.fr/tests/55c4ca586149d1903b3d461e/show

http://www.urssaf.fr/employeurs/baremes/baremes/taux_des_cotisations_du_regime_general.pdf

**Comment by laem** [comment]
Sur cette [page](https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/la-cotisation-maladie---maternit.html) urssaf.fr, le tableau accessible tout en bas, indique une cotisation de 13,1, mais **elle inclut la contribution solidarité autonomie (CSA) de 0,3%**.

![selection_202](https://cloud.githubusercontent.com/assets/1177762/11421950/4a80a522-9438-11e5-80ed-12f21bea925f.png)

Le taux employeur est donc bien de 12,8% + CSA de 0.3%, cette dernière étant déjà incluse dans notre calcul. 
L'article D242-3 du code de la sécu. le confirme.

Merci @jdesboeufs :smile:

**Comment by jdesboeufs** [comment]
Profitez-en pour vérifier que la CSA est bien dans le barème JEI ;)

**Comment by laem** [comment]
> Profitez-en pour vérifier que la CSA est bien dans le barème JEI ;)
#48
