### ISSUE TITLE
Interface avancée : premiers retours de l'open lab du 03 mai 2016

### ISSUE THREAD

**Issue by georges-bayard** [sgmap/cout-embauche#230]
La maquette d’interface avancée est présentée et donne lieu aux remarques suivantes :
- les exonérations de charge pour le recrutement dans les JEI se sont ouvertes que pour certains salariés intégrant ces entreprises : techniciens, ingénieurs, … : cela devrait être précisé dans le simulateur
- S’agissant du résultat de l’estimation, revoir la formulation pour rappeler que ce qui est affiché est le résultat d’une estimation
- Laisser les données saisies en entrée de simulation quand on est dans la partie simulateur avancé
- Utilisation du numéro de l’API Entreprise pour pré-remplir certaines informations : bien mesurer l’impact en terme de difficulté de saisie (le numéro Siret n’est pas une information simple à saisir) au regard de l’intérêt que peut apporter la remontée des informations (nombre de salariés de l’entreprise ; l’information est-elle à jour ?) 
- Sur les résultats détaillés de la simulation, n’afficher le point d’interrogation que si la précision permettant de lever l’ambiguïté n’a pas été levée dans le simulateur avancé
- Réfléchir à une nouvelle présentation par blocs homogènes de la simulation détaillée : classement en fonction du destinataire de la contribution interlocuteur administratif de l’entreprise (URSAFF, maladie, …) ou d’autres critères à définir.
- Dans la simulation avancée, ne pas aligner horizontalement les questions-réponses, car cela casse l'aspect conversation.

**Comment by laem** [comment]
Fait, sauf le point concernant la possibilité de différentes vues des résultats, par risque, par organisme de recouvrement, etc. 
Nécessite de catégoriser les cotisations, voir https://github.com/sgmap/cout-embauche/wiki/Nouvelle-syntax-des-regles @georges-bayard
