### ISSUE TITLE
Contribution patronale au financement des organisations professionnelles et syndicales

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#24]
Nouvelle contribution due sur les rémunérations versées à compter du 1er janvier 2015.
Taux de 0,016% sur la rémunération brute.

**Comment by agathelenahenec** [comment]
http://www.service-public.fr/professionnels-entreprises/actualites/007298.html

**Comment by laem** [comment]
Précédemment dans "Main d'oeuvre"

**Comment by agathelenahenec** [comment]
ok. à afficher anyway en tant que tel
