### ISSUE TITLE
Affiner le calcul d'Accident du travail

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#25]
Deux problèmes distincts sur cette ligne : 
- elle calcule la cotisation comme si celle-ci était au taux de 1,1% alors que le taux est variable selon la nature de l'activité, la taille de l'entreprise et une sorte de système de bonus-malus : faut-il conserver cette ligne alors que l'on ne sait pas la calculer? Ou tenter de trouver un taux moyen? Dans ce cas il faudrait peut-être le préciser quelque part. Ce taux de 1,1% correspond il à un taux moyen? (il semble que les taux soient en général plus élevé que cela). Ce point pourrait être discuté en open lab
- si on conserve cette ligne il faut la déplacer dans les cotisations patronales. Elle se trouve actuellement dans les cotisations salariales.

**Comment by MattiSG** [comment]
J'éclate cette issue en deux : celle-ci, et #31.

**Comment by laem** [comment]
Les taux d'OpenFisca : https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/param/param.xml#L273-L287

**Comment by laem** [comment]
Le taux moyen est très élevé : ~ 3% 
Le calcul actuel est de 1.1%. 
Garder ce taux qui correspond à au "taux bureau", et préciser dans le bloc "non géré" que ce calcul est complexe. 
Pour réellement calculer ce taux, on peut imaginer plusieurs solutions : 
- auto complétion du secteur de la boîte. 
- question simple du type "est-ce une activité sans risque (bureau)"

**Comment by agathelenahenec** [comment]
On pourra proposer à l'open lab deux solutions alternatives : 
- afficher un taux moyen en précisant que c'est un taux moyen avec un lien En savoir plus
- ou afficher un taux "bureau" avec les solutions que tu proposes

**Comment by laem** [comment]
Lien intéressant : http://www.ameli.fr/employeurs/vos-cotisations/le-calcul-des-taux/les-differents-modes-de-tarification_rhone.php

**Comment by laem** [comment]
[Page](https://github.com/sgmap/cout-embauche/wiki/AT-MP) du wiki
