### ISSUE TITLE
Fiabiliser la ligne taxe d'apprentissage

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#26]
Le taux de la taxe d'apprentissage que le calculateur prend en compte est 0,5% Or ce taux n'existe pas et ne correspond ni à un taux moyen ni à un taux maximum (le taux de la taxe d'apprentissage varie en fonction de la taille de l'entreprise et du pourcentage de son effectif apprenti ou VIE ou CIFRE). De plus certaines entreprises en sont exonérées  : 
   - les entreprises employant des apprentis et dont la base d'imposition (l'ensemble des rémunérations) ne dépasse pas 6 fois le Smic annuel (soit 104 067,60 € pour la taxe due en 2015 au titre de 2014, et 104 941 € pour la taxe due en 2016 au titre de 2015),
    - les sociétés civiles de moyens (SCM), sous certaines conditions, lorsque leur activité est non commerciale,
   - les sociétés et personnes morales ayant pour objet exclusif l'enseignement,
   - les groupements d'employeurs composés d'agriculteurs ou de sociétés civiles agricoles bénéficiant eux-mêmes de l'exonération.

Faut-il retenir le taux maximal? (0,6%) Le taux s'appliquant aux entreprises de moins de 2000 salariés n'embauchant aucun apprenti? (0,4%) Un autre taux?
A déterminer et préciser le cas échéant

**Comment by agathelenahenec** [comment]
#40

**Comment by MattiSG** [comment]
Comme vu IRL avec @agathelenahenec et @laem, ces différents taux ne sont plus à jour. Le reste à faire est donc dans #40.
