### ISSUE TITLE
Corriger l'assiette de la CSG CRDS au delà de 4 fois le plafond de la Sécurité sociale (PSS)

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#27]
Au-delà de 4 fois le plafond sécu (PSS = 3170€/mois), l'assiette de la CSG CRDS est 100% de la rem brute (au lieu de 98,25% en dessous). Il semble que le simulateur reste sur toutes les rémunérations sur une assiette de 98,25%.
http://vosdroits.service-public.fr/particuliers/F2971.xhtml

http://embauche.sgmap.fr/tests/55cdf1956149d1903b3d49a9/show

**Comment by laem** [comment]
Quelques exemples ici : 
http://www.compta-online.com/verifier-la-csg-et-la-crds-assiette-et-abattement-plafonne-ao946

**Comment by laem** [comment]
Le taux de 100% est en fait un taux marginal, qui s'applique seulement sur la partie du salaire > à 4 x PSS :smile: . Pas de problème donc, j'ai mis à jour le test.
