### ISSUE TITLE
Page de démo : la rencontre OpenLab du 18/01/2017 est passée

### ISSUE THREAD

**Issue by PhilippeVay** [sgmap/cout-embauche#274]
Bonjour,

la page de démo du simulateur https://embauche.beta.gouv.fr fait référence à une rencontre passée : 

> Notre prochaine rencontre OpenLab aura lieu le mercredi 18 janvier 2017 à 10h, au 86 allée de Bercy, 75012, salle 381-R

qui devrait être archivée ( _Notre précédente rencontre OpenLab a eu lieu le mercredi 18 janvier 2017 à Paris_ ) et/ou complétée / remplacée par une annonce type "La date d'une future rencontre n'est pas encore connue, etc" ou bien remplacée par l'annonce de la future rencontre si elle est vous est déjà connue ou par rien ou qui suis-je pour vous dire ce que vous devriez faire ☺️

**Comment by georges-bayard** [comment]
Bonjour, nous vous remercions pour toute l attention que vous portez au simulateur de coût d embauche. Nous allons remettre à jour l information.

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

28 janv. 2017 14:39:09, PhilippeVay <notifications@github.com> a écrit :



Bonjour,

la page de démo du simulateur https://embauche.beta.gouv.fr fait référence à une rencontre passée :

Notre prochaine rencontre OpenLab aura lieu le mercredi 18 janvier 2017 à 10h, au 86 allée de Bercy, 75012, salle 381-R

qui devrait être archivée ( Notre précédente rencontre OpenLab a eu lieu le mercredi 18 janvier 2017 à Paris ) et/ou complétée / remplacée par une annonce type "La date d'une future rencontre n'est pas encore connue, etc" ou bien remplacée par l'annonce de la future rencontre si elle est vous est déjà connue ou par rien ou qui suis-je pour vous dire ce que vous devriez faire ☺️

**Comment by laem** [comment]
La référence à l'ancienne date est enlevée.
