### ISSUE TITLE
Le fait d'avoir un résultat direct à la saisie du salaire n'incite pas à valider pour voir les questions suivantes

### ISSUE THREAD

**Issue by juliencarnot** [sgmap/cout-embauche#290]
À la première utilisation, j'ai cliqué sur SMIC, et vu un résultat s'afficher en bas. Il m'a fallu quelques secondes pour voir qu'il fallait cliquer sur Valider pour passer à la question suivante et affiner le calcul.

Une barre de progression/timeline dans les questions ou l'obligation de cliquer sur valider pour avoir un résultat serait peut-être utile, sauf si c'est juste moi qui ai marqué un temps d'arrêt sur cette première étape...

**Comment by laem** [comment]
C'était bien l'autre repo le bon :-)
