### ISSUE TITLE
Ajouter affiliation

### ISSUE THREAD

**Issue by MattiSG** [sgmap/cout-embauche#3]
Ajouter un bloc contenant « Fourni par OpenFisca » + logo OpenFisca + lien.

@ppezziardi lien vers openfisca.fr ou vers embauche.sgmap.fr ?

**Comment by MattiSG** [comment]
@cbenz Pour le logo OpenFisca, vous avez un hotlink stable en plusieurs résolutions quelque part ? Ça permettrait de le mettre à jour (voire de faire du tracking).

**Comment by cbenz** [comment]
Oui grâce à ta demande maintenant nous avons des hotlinks ;-)

* Choisis un fichier depuis le répertoire hotlinks [1]
* Construis l'URL type : http://www.openfisca.fr/hotlinks/<filename>

Par exemple :
http://www.openfisca.fr/hotlinks/logo-openfisca-280x200-transparentbg.png

Pour l'instant il n'y a aucune différence de traitement entre les images
du site et le répertoire hotlinks, mais c'est plus explicite de mettre
hotlinks dans l'URL.

En plus de cela tu as le favicon qui est stable lui aussi :
http://www.openfisca.fr/favicon.ico

Sinon pour info j'ai réitéré ma demande à France Stratégie de nous
fournir le logo SVG qu'ils avaient fait, j'attends la réponse. Sinon je
le ferai moi-même.

[1]
https://github.com/openfisca/openfisca-web-site/tree/master/openfisca_web_site/static/hotlinks

**Comment by MattiSG** [comment]
Parfait, merci @cbenz !  :)
