### ISSUE TITLE
Fiabiliser le Fillon pour entreprises de plus de 20 salariés 

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#30]
Les seuls tests jaunes qui restent actuellement sont ceux qui concernent les entreprises de plus de 20 salariés. Cela correspond au post suivant de #6 :  

> Evolution à prévoir du plafond du coefficient applicable
> GAINS ET RÉMUNÉRATIONS VERSÉS PAR : EN 2015 EN 2016 À COMPTER DE 2017
> Les employeurs occupant moins de 20 salariés (employeurs soumis à une cotisation Fnal au taux de 0,10 % sur les rémunérations plafonnées) 0,2795 0,2805 0,2810
> Les employeurs occupant 20 salariés et plus (employeurs soumis à une cotisation Fnal au taux de 0,50 % sur la totalité de la rémunération) 0,2835 0,2845 0,2850
> 
> Source : http://vosdroits.service-public.fr/professionnels-entreprises/F24542.xhtml#N1014E"

Il faut donc de mettre la valeur du coefficient 2015 à 0,2835 pour les entreprises de plus de 20 salariés
Puis relancer les deux tests jaunes : 
http://embauche.sgmap.fr/tests/?keyword=Fillon

**Comment by MattiSG** [comment]
Sur le test http://localhost:9002/tests/55c20c8d6149d1903b3d20a4/show, la description dit :

> (0,2835/0,6)*[1,6*(17490,20/17490,20)] = 0,2835
> Coeff max est égal au plafond donc montant annuel Fillon =
17490,20* 0,2835 = 4958,415
> Montant mensuel = 413,20125€

Or, (0,2835/0,6)*[1,6*(17490,20/17490,20)] = 0,756 et non 0,2835.

Cela peut-il avoir un impact sur les calculs suivants ?

En effet, la mise à jour des coefficients (#29) ne change pas le résultat, et le code [prend bien en compte](https://github.com/openfisca/openfisca-france/blob/7f271621a8ec5091c4035aba3df6162a9fd68762/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py#L247) les tailles d'entreprise. Je vais vérifier que le calcul des tailles d'entreprise à partir du nombre de salariés est bien effectué.

**Comment by MattiSG** [comment]
Ok, je l'ai…  -_-
openfisca/openfisca-france#304

**Comment by MattiSG** [comment]
Besoin de validation des tests préexistants dans OpenFisca pour pouvoir intégrer openfisca/openfisca-france#304.

**Comment by MattiSG** [comment]
Fixed via openfisca/openfisca-france#304.
