### ISSUE TITLE
Supprimer la ligne Main d'oeuvre

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#32]
Cette ligne est un agrégat de plusieurs cotisations et taxes différentes qu'il n'y a pas lieu de calculer ensemble, d'autant que certaines de ces lignes sont calculées de façon redondante en dehors de ce package

**Comment by MattiSG** [comment]
La décomposition sur laquelle les lignes actuelles se base est [chez OpenFisca](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/decompositions/decomp_contrib.xml).

**Comment by laem** [comment]
https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/decompositions/fiche_de_paie_decomposition.xml#L32-L43
