### ISSUE TITLE
Fiabiliser la ligne "Contribution supplémentaire à l'apprentissage"

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#33]
Attention le calcul de cette ligne ne pourra s'effectuer qu'après une évolution de l'interface. Niveau de priorité à définir en open lab (a priori faible).

**Comment by agathelenahenec** [comment]
#38 #39

**Comment by agathelenahenec** [comment]
http://bofip.impots.gouv.fr/bofip/6325-PGP.html

toutes les règles sont là...

**Comment by georges-bayard** [comment]
création d'une ano spécifique sur la prise en compte de l'effectif dans le calcul de la contribution :https://github.com/sgmap/cout-embauche/issues/167. pourrait être réglé de manière détacheable de la question de l'interface à faire évoluer.
