### ISSUE TITLE
Créer et calculer la ligne "FPSPP"

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#36]
http://www.opcalia.com/employeurs/verser-vos-contributions/fpspp-et-repartition-des-taux/

**Comment by MattiSG** [comment]
Pourquoi avoir fermé l'issue ? Si cette cotisation ne doit pas être intégrée, il peut être intéressant de préciser pourquoi, ça pourrait resservir par la suite  :)

**Comment by agathelenahenec** [comment]
ok en fait cette cotisation ainsi que l'ensemble des cotisations relatives à la formation professionnelle sont bien prises en compte sous la ligne "Formation professionnelle" dont le calcul est juste
c'était donc une erreur de ma part
le droit ici : http://www.opcadefi.fr/ocpa-defi/reforme-de-la-formation-professionnelle/financement-de-la-formation-professionnelle.html

par contre la ligne formation professionnelle ne marche pas pour toutes les entreprises > 9 salariés, je recrée une issue spécifique (et des tests)
