### ISSUE TITLE
Corriger la ligne Taxe d'apprentissage

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#40]

**Comment by laem** [comment]
Cette ligne devrait pouvoir être calculée facilement : 0.68% pour toutes les entreprises. 
Dans OpenFisca, [param.xml distingue](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/param/param.xml#L1472-L1505) les entreprises de + ou - de 250 salariés. et ajoute une "Contribution additionnelle au développement de l'apprentissage" qui semble obsolète. 
Voir ce qui est calculé dans la formule.

**Comment by laem** [comment]
La réforme 2014 de la taxe d'apprentissage se résume, pour le financement, à :
-  une Taxe d’apprentissage avec un taux unique: 0,68 % de la masse salariale brute base, sécurité sociale (fusionde la Taxe d’apprentissage à 0,5 % et de la contribution au développement à l’apprentissage qui représentait 0,18 % de la masse salariale des entreprises)
[source](https://www.univ-paris1.fr/fileadmin/Service_MUE/Apprentissage/Guide_pratique_taxe_d_apprentissage_2015_CCI.pdf)
- une contribution supplémentaire à l’apprentissage (CSA) qui conserve ses principes d’assujettissement et de proportionnalité mais, qui, lorsque l’entreprise y est assujettie, finance, depuis cette année, comme le Quotade la Taxe d’apprentissage les CFA ou sections d’apprentissage

**Comment by laem** [comment]
La taxe d'apprentissage / contribution au développement est corrigée dans la version actuelle. Pas la CSA.
