### ISSUE TITLE
Marquer comme instable la ligne "Accident du travail"

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#42]
#25

**Comment by laem** [comment]
Deux solutions possibles : 
- un astérisque avec explication en bas de la page
Avantage : très simple à implémenter et familier
- une icône et une explication au survol
Avantage : possibilité d'explication individuelle (voir d'autres icônes), plus moderne. 

![cotisation-instables](https://cloud.githubusercontent.com/assets/1177762/10305624/86c14882-6c21-11e5-938b-e81154126019.png)

**Comment by laem** [comment]
Discussion avec Matti : il serait bon de pouvoir séparer les lignes "imprécises" des lignes "à venir". 
Sur les lignes imprécises, avec l'un des indicateurs proposés sur l'image, on ajouterait un +-X € si l'on dispose d'une estimation de l'erreur potentielle. Cela complexifie pas mal l'interface, et je serais d'avis d'afficher ce +- seulement au survol. 
Dans le bloc "à venir" séparé des autres lignes, on parlerait d'estimation de l'impact en %, avec potentiellement un petit texte expliquant l'avancement de l'implémentation.

**Comment by laem** [comment]
Discussion avec Matti : il serait bon de pouvoir séparer les lignes "imprécises" des lignes "à venir".
Sur les lignes imprécises, avec l'un des indicateurs proposés sur l'image, on ajouterait un +-X € si l'on dispose d'une estimation de l'erreur potentielle. Cela complexifie pas mal l'interface, et je serais d'avis d'afficher ce +- seulement au survol.
Dans le bloc "à venir" séparé des autres lignes, on parlerait d'estimation de l'impact en %, avec potentiellement un petit texte expliquant l'avancement de l'implémentation.

**Comment by agathelenahenec** [comment]
Ok pour distinguer imprécis et à venir. Ceci dit, afficher l'écart en euro des imprécises est très complexes puisque par exemple dans certains cas l'imprécision ne s'applique qu'à un certain niveau de salaire ou pour une certaine taille d'entreprise. Calculer cela et afficher ce calcul uniquement quand les critères de l'imprécision sont remplis serait à mon sens encore plus long que de faire la correction sur les quelques lignes concernées (AF, ARRCO, Formpro, Maladie, CSG/CRDS). Comme discuté l'autre fois, corriger ces anomalies me parait prioritaire dès que l'on aura indiqué sur les lignes à venir qu'elles sont à venir (ce qui est en réalité le cas des lignes qu'on avait qualifiées d'instables)

**Comment by laem** [comment]
OK. Donc on garderait l'idée du bloc "à venir" dans un premier temps, et on se concentrerait sur la correction des 5 "instables".

**Comment by laem** [comment]
Instable = non calculable avec l'interface actuelle
