### ISSUE TITLE
Permettre la validation des valeurs numériques sous Firefox et IE

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#43]
![selection_150](https://cloud.githubusercontent.com/assets/1177762/9906691/a0744310-5c8b-11e5-88ca-a1cc0cd148bf.png)

Arrive seulement après édition du placeholder, n'arrive pas sur Chrome.

**Comment by MattiSG** [comment]
Merci pour ce retour. C'est très certainement du au fait que les valeurs décimales ne sont interprétées correctement par Firefox que si on précise `lang="fr"` sur l'`<input>`.

**Comment by MattiSG** [comment]
Problème corrigé par `lang="fr"` dans FF, mais toujours présent sous IE11 et Edge/Win10.
