### ISSUE TITLE
Comment parler des exonérations fiscales dans le résultat du widget

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#44]

**Comment by MattiSG** [comment]
Délicat à traiter : il faudrait dans l'idéal trouver un moyen d'évaluer le montant d'impôts sur lesquels l'exonération portera.

Le mieux est probablement de construire une représentation claire du résultat, afin que l'utilisateur comprenne bien qu'il s'agit d'une exonération _potentielle_ dépendant (entre autres) de son bénéfice, et non d'une exonération systématique comme les autres types d'exos.

**Comment by agathelenahenec** [comment]
Concernant le CICE le problème n'existe pas puisqu'il s'agit d'un crédit d'impôts. Pour les autres exonérations en effet il faudra voir ce qu'on peut faire c'est d'ailleurs ce qu'on avait indiqué en atelier au chef d'entreprise qui avait posé la question. Je pense quand même que ça mérite que je m'y penche car les montants en jeu peuvent être importants et donc décisifs...

**Comment by MattiSG** [comment]
Question OpenLab : comment rendre lisible le fait qu'il faut avancer la trésorerie pendant un an ?
