### ISSUE TITLE
Complémentaire santé obligatoire

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#45]

**Comment by MattiSG** [comment]
Peux-tu ajouter toutes les références pertinentes (législatives et autres) sur les cotisations en question ? Ça va être délicat à implémenter sinon  ;)

**Comment by agathelenahenec** [comment]
c'est pour ça que je me le suis auto assigné, je veux pas oublier mais là pas le temps

**Comment by MattiSG** [comment]
Ok !

**Comment by laem** [comment]
Une suggestion utilisateur est de laisser un champs libre pour la mutuelle, qui irait dans la base de calcul de la CSG notamment. J'ai peur que cela complexifie l'interface. 
L'idéal serait de trouver le prix de marché du "panier de soins minimum" et d'en afficher la moitié... @georges-bayard

**Comment by georges-bayard** [comment]
On peut aussi afficher un coût minimum de 25 euros.
Vu sur internet : « Les spécialistes s’accordent aujourd’hui sur un prix mensuel à l’équilibre de 25 euros… »
http://www.protection-sociale-entreprise.fr/article/panier-de-soins-ani-quel-juste-prix

On peut proposer à l’open lab des options :

-          Champ saisissable (avec les inconvénients que tu dis)

-          Montant minimal forfaitaire (25 € ?)

-          Ne rien faire et mettre dans les conditions générales que le calcul est hors mutuelle

De : Mael [mailto:notifications@github.com]
Envoyé : mercredi 10 février 2016 09:13
À : sgmap/cout-embauche
Cc : BAYARD Georges
Objet : Re: [cout-embauche] Afficher réforme financement mutuelles par les employeurs (#45)


Une suggestion utilisateur est de laisser un champs libre pour la mutuelle, qui irait dans la base de calcul de la CSG notamment. J'ai peur que cela complexifie l'interface.
L'idéal serait de trouver le prix de marché du "panier de soins minimum" et d'en afficher la moitié... @georges-bayard<https://github.com/georges-bayard>

**Comment by laem** [comment]
Décision retenue : pour l'instant, afficher une ligne mutuelle à 0€ et explications. Dans un deuxième temps, autoriser la saisie.
