### ISSUE TITLE
Ajouter la possibilité d'effectuer les calculs en partant du salaire net et du salaire super brut

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#46]

**Comment by laem** [comment]
Regarder la classe `salaire_de_base` dans `inversion_revenus.py` : 
> Calcule le salaire brut à partir du salaire imposable ou sinon du salaire net

**Comment by laem** [comment]
Le gros besoin, partir du salaire net, est intégré aujourd'hui :-)
