### ISSUE TITLE
Fiabiliser le calcul pour les jeunes entreprises innovantes

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#48]

**Comment by MattiSG** [comment]
A-t-on des tests sur le sujet ?

**Comment by laem** [comment]
Est-ce une exonération sur cotisation ou fiscale ?

**Comment by agathelenahenec** [comment]
les deux mon capitaine : 
"Les entreprises reconnues comme JEI bénéficient d'une exonération des cotisations patronales de sécurité sociale pour les personnels participant à la recherche et des avantages fiscaux suivants :

    exonération totale d'impôt sur les bénéfices pour les résultats du premier exercice  ou de la première période d'imposition bénéficiaire et application d'un abattement de 50 % au titre de l'exercice ou de la période d'imposition bénéficiaire suivant ;
    sur délibération des collectivités locales, exonérations pendant 7 ans de taxe foncière sur les propriétés bâties (TFPB), de cotisation foncière des entreprises (CFE) et de cotisation sur la valeur ajoutées des entreprises (CVAE) ;
    sous certaines conditions, exonération des plus-values de cession de parts ou actions des JEI détenues par des personnes physiques.

Les jeunes entreprises innovantes ont également la possibilité de bénéficier de la restitution immédiate de leur créance de crédit impôt recherche constatée pendant une année au cours de laquelle elles bénéficient de la qualification de jeune entreprise innovante." (http://www.impots.gouv.fr/portal/dgi/public/popup?espId=2&typePage=cpr02&docOid=documentstandard_1656)

Concernant le calcul des exonérations sociales : 
https://www.urssaf.fr/portail/home/employeur/beneficier-dune-exoneration/exonerations-ou-aides-liees-au-s/jeunes-entreprises-innovantes/quelle-exoneration.html

**Comment by jdesboeufs** [comment]
Je peux vous aider à fiabiliser ce point, j'ai accès au barème réel et au calculateur DUCS sur mon compte urssaf.fr.

**Comment by laem** [comment]
> vérifier que la CSA est bien dans le barème JEI
