### ISSUE TITLE
Prendre en compte le CIR

### ISSUE THREAD

**Issue by descl** [sgmap/cout-embauche#5]
Bonjour pour mieux considérer le coût d'une embauche nous aimerions aussi avoir une estimation du Crédit impôt Recherche voir du Crédit Impôt Innovation.
http://www.impots.gouv.fr/portal/dgi/public/popup?espId=2&typePage=cpr02&docOid=documentstandard_4533
Merci pour l'outil, Christophe

**Comment by MattiSG** [comment]
Bonjour Christophe et merci pour cette suggestion !

Nous nous focalisons actuellement sur le statut d'apprenti et sur la taxe transport. Si nous en avons l'occasion, nous évaluerons la complexité que représente l'ajout du CIR/CII dans le simulateur.

À tout hasard, peut-être @benjello pourra nous renseigner s'il a déjà réfléchi au problème. À défaut, nous essaierons d'y jeter un œil la semaine prochaine  :)

Bonne journée,
Matti

**Comment by agathelenahenec** [comment]
Bonjour Christophe 

Après examen des dispositifs du CIR et du CII, il nous a semblé que ceux-ci n'entrent pas vraiment dans le champ de l'outil simulateur d'embauche du fait même de leur nature de crédits d'impôt (et non réductions de charges). En effet, ils n'ont techniquement pas d'influence sur le salaire super brut, brut ou net car ils viennent s'imputer sur l'IS ou sur l'IR, en fonction du statut de l'entreprise. Ce que l'outil pourrait donc afficher est seulement le crédit d'impôt que la dépense de personnel concernée serait susceptible d'induire, ce qui sort un peu du périmètre de notre simulateur et serait très théorique puisque nous ne connaissons ni le montant de l'IR, ni le recours éventuel à d'autres réductions (soumises à plafonnement) etc.
Enfin, il semble que la difficulté de ces dispositifs soit surtout de sécuriser son éligibilité (type d'entreprise, nature de la dépense, nature de l'activité) auprès de la Direccte. Le calcul en lui-même est relativement aisé puisqu'il s'agit d'un pourcentage simple (20% dans le cas du CII dans la limite de 400.000€, 30% pour le CIR et 50% dans les DOM jusqu'à 100M€).

N'hésitez pas à nous faire part de vos remarques si cette réponse vous paraît insatisfaisante, ou à nous faire d'autres suggestions.

Bien cordialement,

Agathe
