### ISSUE TITLE
Fonds national action logement

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#57]
Premier point
---------------------------
Le nom de cette cotisation entretient une **confusion** entre :
- la `Participation des employeurs à l'effort de construction`, aussi appelée `dispositif Action logement` depuis 2009
- le fonds national d'aide au logement (FNAL).

La FNAL est bien une cotisation employeur, c'est donc probablement d'elle que l'on veut parler. L'autre doit-elle être intégré dans notre calcul ?

Deuxième point
------------------------------

C'est bien une **cotisation employeur** et non une cotisation employé, comme elle est présentée actuellement dans l'interface.

**Comment by laem** [comment]
C'est d'ailleurs cette cotisation qui entraîne une différence entre notre cumul des cotisations employeur et le salaire net renvoyé par open fisca.

**Comment by agathelenahenec** [comment]
Premier point : il faut effectivemebt renommer la ligne correctement et la placer dans les cots employeurs mais participation à l'effort de construction est bien une autre ligne, qui est calculée (correctement) et affichée dans le simuateur

**Comment by laem** [comment]
:+1:
