### ISSUE TITLE
Corriger le calcul de l'allègement Fillon

### ISSUE THREAD

**Issue by MattiSG** [sgmap/cout-embauche#6]
Le montant de l'allègement Fillon est erroné (openfisca/openfisca-france#287).

La raison en est que cet allègement est calculé sur la paie annuelle (openfisca/openfisca-france#288), et que le simulateur ne fonctionne actuellement qu'en mensuel.

Il faut donc mettre à jour l'API `/formula` pour qu'elle répercute les montants sur tous les mois de l'année civile.

**Comment by MattiSG** [comment]
- [ ] Vérifier cumul avec statut JEI.

**Comment by agathelenahenec** [comment]
Evolution à prévoir du coefficient applicable 
GAINS ET RÉMUNÉRATIONS VERSÉS PAR : 	EN 2015 	EN 2016 	À COMPTER DE 2017
Les employeurs occupant moins de 20 salariés (employeurs soumis à une cotisation Fnal au taux de 0,10 % sur les rémunérations plafonnées) 	0,2795 	0,2805 	0,2810
Les employeurs occupant 20 salariés et plus (employeurs soumis à une cotisation Fnal au taux de 0,50 % sur la totalité de la rémunération) 	0,2835 	0,2845 	0,2850

**Comment by agathelenahenec** [comment]
Pour fiabiliser Fillon, il faudrait vérifier que les changements suivants sont bien pris en compte dans le code : 
A partir du 1er janvier 2015 
- la cotisation FNAL, la contribution de solidarité pour l'autonomie et la cotis accident du travail (dans la limite de 1% pour cette dernière) entrent dans le champ de la réduction.
- la nouvelle formule de calcul du coefficient est la suivante :
(T /0,6) x [1,6 x (SMIC annuel / rémunération annuelle brute) - 1] ou T = valeur maximale du coefficient telle qu'indiquée dans le post ci dessus (attention variation entre 2015 et 2017 et distinction entre + de 20 et - de 20 salariés). Résultat arrondi à 4 décimales le plus proche si inférieur à ces plafonds. Sinon les plafonds s'appliquent.

**Comment by agathelenahenec** [comment]
Les seuils (- de 20 ou + de 20 entreprises) ne semblent pas pris en compte pour le calcul du Fillon

**Comment by agathelenahenec** [comment]
Le simulateur ne donne des résultats fiables à quelques euros près qu'au niveau du SMIC, la marge d'erreur augmente avec la rémunération

**Comment by MattiSG** [comment]
> Les seuils (- de 20 ou + de 20 entreprises) ne semblent pas pris en compte

Ok, super ! As-tu pu créer des tests sur ce point ?

**Comment by agathelenahenec** [comment]
Oui, deux au niveau du SMIC et deux à 1,4 SMIC

**Comment by agathelenahenec** [comment]
En gros sur le Fillon à ce stade il faudrait vérifier la formule calcul, faire le calcul sur 12 mois, prendre en compte le nombre de salariés, mettre à jour la valeur du SMIC et des coefficients, ajouter les nouvelles cotisations qui entrent dans le champ, puis relancer les 5 tests créés...

**Comment by MattiSG** [comment]
On va commencer par le calcul sur 12 mois, il est possible que ça débloque le reste  :)

**Comment by MattiSG** [comment]
Hallelujah ! Correctif déployé* pour la prise en compte des 12 mois ! On passe [tous les tests](http://embauche.sgmap.fr/tests/?keyword=Fillon) < 20 salariés au vert, et les > 20 salariés en jaune  :)

Les tests jaunes sont certainement dus à la revalorisation 2015.

Pour améliorer la lisibilité, je ferme cette issue et en ouvre une autre spécifique aux mises à jour des plafonds 2015-2016-2017.

poke @ppezziardi @jdesboeufs

> * Déploiement effectué sur openfisca.sgmap.fr, pour l'intégration sur openfisca.fr suivre openfisca/openfisca-web-api#36.
