### ISSUE TITLE
Fiabilité des détails

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#61]
Nos lignes de détail explicitent les calculs du super brut et du net, et doivent donc pouvoir être utilisées pour recalculer ces montants, or ce n'est pas le cas actuellement.

La branche `details-quality-check` corrige les problèmes (oublis de lignes, lignes dans la mauvaise catégorie, duplication (main d'oeuvre est un aggrégat), au moins pour le cas par défaut du simulateur, à l'exception de la ligne contribution au développement de l'apprentissage, que nous n'affichons pas même si elle est prise en compte dans le calcul du salaire super brut (à tort, car obsolète #40 ).

**Comment by MattiSG** [comment]
Que reste-t-il à faire dans `details-quality-check` pour ouvrir une PR ?

**Comment by laem** [comment]
Cette branche est basée sur la PR #62, à laquelle il manquait le test d'intégration du tooltip, que je viens de pousser.
