### ISSUE TITLE
Versionner le widget

### ISSUE THREAD

**Issue by MattiSG** [sgmap/cout-embauche#7]
En tant que réutilisateur,
Je peux faire intégrer une version spécifique du widget,
Pour ne pas subir de mises à jour sans en être informé

- - - - -

- [x] Releases.
- [ ] Documenter l'intégration.
- [ ] Ajouter [Subresource Integrity](http://www.w3.org/TR/SRI/).
- [ ] Communiquer.

**Comment by laem** [comment]
Ce besoin n'est pas (re)venu, les intégrateurs étant plutôt ravis que la mise à jour soit automatique.
