### ISSUE TITLE
Arrondir les résultats du calcul 

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#84]
> Cela coûtera 1576~~,24~~ € par mois à mon entreprise.

> Mon salarié.e touchera 1136~~,00~~ € par mois.

Les centimes dans ces résultats agrégés n'ont pas grand intérêt, et surtout peuvent inciter certains à confondre simulateur et calculateur. 
Les lignes de détail gardent leur précision à deux décimales.

**Comment by MattiSG** [comment]
:+1:

**Comment by laem** [comment]
Fixed by #87
