### ISSUE TITLE
Consolider les pages statiques

### ISSUE THREAD

**Issue by MattiSG** [sgmap/cout-embauche#90]
La page de présentation [embauche.sgmap.fr](http://embauche.sgmap.fr) est aujourd'hui servie comme un [module statique](https://github.com/sgmap/paie-www) depuis l'[API Paie](https://github.com/sgmap/paie-api) (dépréciée).

Pour en simplifier la modification, et pour effacer définitivement la complexité associée, il faudrait consolider cet élément, ainsi que la [documentation de l'API](https://github.com/sgmap/paie-api/tree/master/ui), dans un seul endroit.

Toutes ces pages étant statiques (la doc est générée par l'API `/formula` d'OpenFisca), le plus simple serait probablement d'utiliser la branche `gh-pages` de ce dépôt pour toutes les héberger.

Je suggère donc l'organisation suivante :

- [ ] Migrer le contenu actuel, à l'exception de `index.html` et `dist`, depuis la branche `gh-pages` vers une branche `master`. On garde ainsi la compatibilité avec les modalités de distribution actuelles et on nettoie la branche principale.
- [ ] Renommer `index.html` en `demo.html` ou autre.
- [ ] Récupérer le contenu de `paie-www` (la page d'accueil) et l'intégrer dans `gh-pages`. Cela serait fait de préférence avec un [`git subtree`](https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging) pour ne pas perdre l'historique.
- [ ] Récupérer [la partie](https://github.com/sgmap/paie-api/tree/master/ui) qui sert la documentation d'API Swagger et l'intégrer dans `gh-pages`, probablement dans `doc.html` ou `doc/index.html`. Là encore, de préférence avec un `git subtree` pour conserver l'historique.

Cela simplifiera énormément la modification de la page d'accueil.

En revanche, la publication dans `dist` sera encore plus douloureuse si elle n'est pas outillée, puisque le changement de branche se fera avec des fichiers _untracked_. Il serait donc probablement pertinent d'outiller cette publication. Je suggèrerais de le faire en intégration continue ([section  `deploy`](https://circleci.com/docs/introduction-to-continuous-deployment) dans CircleCI). À défaut, possibilité de s'inspirer [ici](https://github.com/shinnn/gulp-gh-pages).

**Comment by laem** [comment]
:+1:

**Comment by laem** [comment]
En fait, je pense que c'est plus simple de garder la page d'accueil du projet et la doc de l'API dans paie-www, sur la branche gh-pages. 
Ça permet de ne pas mélanger les deux, pour nous mais surtout pour un contributeur au widget : il n'a pas a priori à se soucier de la page d'accueil ni de la doc de l'API.

J'ai d'ailleurs commencé une mise à jour de cette page d’accueil :construction_worker:

**Comment by laem** [comment]
Voir https://github.com/sgmap/paie-www
