### ISSUE TITLE
Calculer le coût d'embauche d'un salarié en CDD

### ISSUE THREAD

**Issue by agathelenahenec** [sgmap/cout-embauche#92]
Spécificités trouvées pour CDD : 

- prime de précarité 10%
- contrib spécifique CIF CDD
- majoration de la part patronale de la cotisation d'assurance chômage

**Comment by agathelenahenec** [comment]
Majoration de la contrib patronale assurance chômage : 
https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/lassurance-chomage-et-lags/la-majoration-de-la-contribution/les-cdd-concernes-par-lapplicati.html#FilAriane

EN RESUME... : 

La majoration de la contribution patronale d’assurance chômage est applicable aux contrats de travail à durée déterminée remplissant les trois conditions suivantes :

    il s’agit d’un CDD dit d’usage ou le motif du CDD est l’accroissement temporaire d’activité,
    le CDD a une durée initiale inférieure ou égale à trois mois,
    la relation contractuelle ne se poursuit pas en CDI (contrat à durée indéterminée)

La contribution majorée est calculée sur les rémunérations servant de base à la détermination des cotisations de Sécurité sociale.

Les rémunérations dépassant 4 fois la valeur de plafond de Sécurité sociale applicable sont exclues de la base de calcul de cette majoration (comme de celle de la cotisation de base).

Taux : 
Si motif = contrat d'usage : majoration de 0,5% (taux global 4,5 au lieu de 4)
Si motif = accroissement temporaire d'activité : si CDD un mois ou moins, majoration de 3%, si CDD de plus de 1 mois à 3 mois inclus, majoration de 1,5%.


Pour la prime de précarité versée à la fin du CDD, le taux de contribution appliqué à cette prime est celui en vigueur à la date de versement de cette rémunération.

Exemple d’un CDD conclu dans le cadre d’un accroissement temporaire d’activité pour une durée initiale d’1 mois, renouvelé pour 2 mois. La prime de précarité est versée à l’issue du contrat en même temps que le dernier salaire. Elle est soumise au taux de contribution applicable au renouvellement, soit 5,5 % (4 % + 1,5 %).

La majoration s’applique au CDD conclu pour accroissement temporaire d’activité et au CDD d’usage, dont la durée est inférieure ou égale à 3 mois.

En cas d’embauche par l’employeur en CDI à l’issue du CDD, la majoration n’est plus due.

Les montants indûment versés au titre de la majoration CDD sont déduits du montant des cotisations et contributions dues au titre de la déclaration sur laquelle est affectée la régularisation.

Cette régularisation est réalisée avec la première déclaration Urssaf adressée suite à l’embauche sous CDI ou à la transformation du contrat à durée déterminée en CDI.

**Comment by agathelenahenec** [comment]
Prime de précarité : 
L'indemnité de fin de contrat n'est pas due dans les cas suivants :

    - embauche en CDI à l'issue du CDD (y compris lorsque le CDD a été renouvelé),
    - refus d'un CDI proposé au salarié 
    - rupture anticipée du contrat à l'initiative du salarié, ou faute grave ou pendant période essai
    - emploi saisonnier ou emploi pour lequel l'usage exclut le recours à un CDI,
    - contrat aidé (contrat unique d'insertion - CUI, contrat de professionnalisation, emploi d'avenir, emploi d'avenir professeur, CDD senior) sauf si une convention collective prévoit le contraire,
    - contrat pour lequel l'employeur s'est engagé à assurer un complément de formation professionnelle au salarié,
    - contrat conclu avec un jeune pendant ses vacances scolaires ou universitaires.

L'indemnité de fin de contrat est égale au minimum à 10 % de la rémunération brute totale versée durant le contrat. Toutefois, ce pourcentage peut être limité à 6 % par une convention ou un accord collectif de branche étendu...

L'indemnité est versée à l'issue du contrat en même temps que le dernier salaire et doit figurer sur le bulletin de paye correspondant.

En cas de renouvellement du CDD, l'indemnité est versée à l'issue du second contrat.

Elle est soumise aux cotisations au même titre que les autres composantes de la rémunération brute globale...

**Comment by agathelenahenec** [comment]
Concernant la contribution CIF CDD c'est plus simple : 1% des rémunérations versées aux salariés en CDD, et ce quelle que soit la taille de l'entreprise

**Comment by agathelenahenec** [comment]
Autre point à adresser : l'indemnité compensatrice de congés payés...

**Comment by laem** [comment]
#### Qu’est-ce que l’indemnité compensatrice de congés payés ?

Elle est due quelle que soit la durée du contrat, dès lors que les congés n’ont pu être pris avant la fin du contrat.

Versée au terme du contrat, l’indemnité compensatrice est au moins égale à 10 % de la rémunération brute perçue pendant toute la durée du contrat, y compris l’indemnité de fin de contrat.

**Comment by laem** [comment]
A été retenu pour une version 1 de la saisie CDD : 
- Ajouter le CIF CDD (1%)
- Ajouter l'indemnité de fin de contrat. Même si elle n'est pas due pour beaucoup de cas, son montant élevé la rend indispensable

Dans une version 2, nous intégrerons davantage de spécificités, qui nécessitent des saisies supplémentaires.
