### ISSUE TITLE
Mettre à jour les cotisations testables dans Ludwig

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#93]
![selection_196](https://cloud.githubusercontent.com/assets/1177762/11143202/bcf053c2-89f3-11e5-9e85-4e9a38a3a51d.png)

**Comment by laem** [comment]
@MattiSG Il faudrait qu'on parle des évolutions de Ludwig...

**Comment by MattiSG** [comment]
@laem https://github.com/sgmap/ludwig-ui/issues

**Comment by MattiSG** [comment]
Pour les intitulés : https://github.com/sgmap/paie-tests/blob/master/config.json
