### ISSUE TITLE
Zones aidées

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#99]
Il n'y *aurait* plus d’exonérations sociales pour les entreprises. 
Il y a toujours des exonérations fiscales. 

### Exonération d'impôts sur les bénéfices + fonciers
https://www.service-public.fr/professionnels-entreprises/vosdroits/F31149 
(plein de conditions : CA, capital, salariés long-terme...)

### Exonération d'impôts sur les bénéfices + fonciers
https://www.service-public.fr/professionnels-entreprises/vosdroits/F31139
(conditions plus simples)

### Exonérations de cotisations sociales 
https://www.service-public.fr/professionnels-entreprises/vosdroits/F31048
Important : 
> jusqu'au 23 février 2014, ce dispositif d'exonération concernait aussi les embauches en zone de redynamisation urbaine (ZRU). Les ZRU sont supprimées à partir du 1er janvier 2015.
[Article sur la suppression](https://www.service-public.fr/professionnels-entreprises/actualites/007002)

*Sauf que*, les BER, ZRR et ZRD [devraient être supprimées](http://www.gerantdesarl.com/2510_fin-des-reductions-de-charges-sociales-dans-les-ber-les-zrr-et-les-zrd) par le PLFSS 2016. 

Le gouvernement prévoit le 7 octobre : 
> Article 10 : Suppression progressive des exonérations de cotisations patronales applicables aux bassins d'emploi à redynamiser (BER), aux zones de restructuration de la défense (ZRD) et aux zones de revitalisation rurale (ZRR).

*Mais* la première lecture adoptée par l'AN le 27 octobre [supprime](http://www.assemblee-nationale.fr/14/ta/ta0600.asp) cet article 10 (Amendements nos 293 , 331 , 339 , 651 , 930)

**Comment by laem** [comment]
@agathelenahenec @jdesboeufs

**Comment by agathelenahenec** [comment]
ok en plus on aura pas de sitôt le fin mot de l'histoire car la commission mixte paritaire sur le PLFSS vient d'échouer (c'est très rare). donc le texte repart en nouvelle lecture à l'AN ensuite il y aura encore une lecture au Sénat et éventuellement le dernier mot de l'Assemblée si ils sont pas d'accord. Donc on a le temps (mais ça sera pas après le 31 décembre en tout cas).

**Comment by laem** [comment]
Transféré sur le wiki https://github.com/sgmap/cout-embauche/wiki/Zones-aidées

**Comment by laem** [comment]
**ATTENTION** Ces éxonérations ne peuvent être cumulées avec la réduction générale (Fillon) !

**Comment by laem** [comment]
Au sujet des zones aidées, voir le wiki https://github.com/sgmap/cout-embauche/wiki/Zones-aidées. 
Pour l'implémentation dans le simulateur, voir #169.
